<?php

/**
 * This is the model base class for the table "tbl_books".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Books".
 *
 * Columns in table "tbl_books" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $book_image
 * @property string $book_name
 * @property string $book_author
 * @property string $book_publisher
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $book_year
 * @property integer $status
 * @property string $book_description
 *
 */
abstract class BaseBooks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_books';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Books|Books', $n);
	}

	public static function representingColumn() {
		return 'book_image';
	}

	public function rules() {
		return array(
			array('created_at, updated_at, book_year, status', 'numerical', 'integerOnly'=>true),
			array('book_image, book_name, book_author, book_publisher', 'length', 'max'=>255),
			array('book_description', 'safe'),
			array('book_image, book_name, book_author, book_publisher, created_at, updated_at, book_year, status, book_description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, book_image, book_name, book_author, book_publisher, created_at, updated_at, book_year, status, book_description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'book_image' => Yii::t('app', 'Book Image'),
			'book_name' => Yii::t('app', 'Book Name'),
			'book_author' => Yii::t('app', 'Book Author'),
			'book_publisher' => Yii::t('app', 'Book Publisher'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'book_year' => Yii::t('app', 'Book Year'),
			'status' => Yii::t('app', 'Status'),
			'book_description' => Yii::t('app', 'Book Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('book_image', $this->book_image, true);
		$criteria->compare('book_name', $this->book_name, true);
		$criteria->compare('book_author', $this->book_author, true);
		$criteria->compare('book_publisher', $this->book_publisher, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('book_year', $this->book_year);
		$criteria->compare('status', $this->status);
		$criteria->compare('book_description', $this->book_description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}