<?php

/**
 * This is the model base class for the table "tbl_ward".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ward".
 *
 * Columns in table "tbl_ward" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $wardid
 * @property string $name
 * @property string $type
 * @property string $location
 * @property string $districtid
 *
 */
abstract class BaseWard extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_ward';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ward|Wards', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('wardid, name, type, location, districtid', 'required'),
			array('wardid, districtid', 'length', 'max'=>5),
			array('name', 'length', 'max'=>100),
			array('type, location', 'length', 'max'=>30),
			array('wardid, name, type, location, districtid', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'wardid' => Yii::t('app', 'Wardid'),
			'name' => Yii::t('app', 'Name'),
			'type' => Yii::t('app', 'Type'),
			'location' => Yii::t('app', 'Location'),
			'districtid' => Yii::t('app', 'Districtid'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('wardid', $this->wardid, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('districtid', $this->districtid, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}